import { StyleSheet } from 'react-native';
import { theme } from '../theme';

export const styles = StyleSheet.create({
  scrollPage: {
    padding: theme.spacing.lg,
    gap: theme.spacing.md,
    paddingBottom: 96,
  },
  fullScreen: {
    flexGrow: 1,
    justifyContent: 'center',
    padding: theme.spacing.lg,
  },
  fullScreenCenter: {
    flex: 1,
    justifyContent: 'center',
    padding: theme.spacing.lg,
  },
  welcomeWrap: {
    gap: 16,
    padding: 18,
    borderRadius: theme.radius.xl,
    backgroundColor: theme.colors.surface,
    borderWidth: 1,
    borderColor: theme.colors.borderSoft,
    shadowColor: '#000',
    shadowOpacity: 0.28,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 10,
  },
  brandMark: {
    width: 52,
    height: 52,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: theme.colors.surfaceRaised,
  },
  welcomeTitle: { color: theme.colors.text, fontSize: 34, fontWeight: '900' },
  welcomeSub: { color: theme.colors.textMuted, fontSize: 15, lineHeight: 22 },
  pillRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  primaryButton: {
    backgroundColor: theme.colors.primary,
    borderRadius: theme.radius.pill,
    paddingVertical: 14,
    paddingHorizontal: 18,
    alignItems: 'center',
  },
  primaryButtonText: { color: theme.colors.background, fontWeight: '900' },
  secondaryButton: {
    backgroundColor: theme.colors.surfaceRaised,
    borderRadius: theme.radius.pill,
    paddingVertical: 14,
    paddingHorizontal: 18,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: theme.colors.borderSoft,
  },
  secondaryButtonText: { color: theme.colors.text, fontWeight: '800' },
  linkText: { color: theme.colors.primary, textAlign: 'center', fontWeight: '700' },
  onboardingCard: {
    gap: 12,
    padding: 20,
    borderRadius: theme.radius.xl,
    backgroundColor: theme.colors.surface,
    borderWidth: 1,
    borderColor: theme.colors.borderSoft,
  },
  onboardingIcon: {
    width: 52,
    height: 52,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: theme.colors.surfaceRaised,
  },
  onboardingStep: { color: theme.colors.primary, fontWeight: '800', fontSize: 12 },
  onboardingTitle: { color: theme.colors.text, fontSize: 24, fontWeight: '900' },
  onboardingSub: { color: theme.colors.textMuted, lineHeight: 22 },
  pagerDots: { flexDirection: 'row', justifyContent: 'center', gap: 8, marginTop: 8, marginBottom: 16 },
  dot: { width: 8, height: 8, borderRadius: 8, backgroundColor: theme.colors.border },
  dotActive: { width: 28, backgroundColor: theme.colors.primary },
  formCard: {
    gap: 14,
    padding: 20,
    borderRadius: theme.radius.xl,
    backgroundColor: theme.colors.surface,
    borderWidth: 1,
    borderColor: theme.colors.borderSoft,
  },
  formTitle: { color: theme.colors.text, fontSize: 26, fontWeight: '900' },
  formSub: { color: theme.colors.textMuted, lineHeight: 22 },
  input: {
    backgroundColor: theme.colors.surfaceRaised,
    borderWidth: 1,
    borderColor: theme.colors.borderSoft,
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 12,
    color: theme.colors.text,
  },
  topBar: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  topKicker: { color: theme.colors.textMuted, fontSize: 12, fontWeight: '700' },
  topTitle: { color: theme.colors.text, fontSize: 28, fontWeight: '900' },
  modeSwitchCard: {
    padding: 12,
    borderRadius: 16,
    backgroundColor: theme.colors.surface,
    borderWidth: 1,
    borderColor: theme.colors.borderSoft,
    gap: 10,
  },
  modeSwitchHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 10,
  },
  modeSwitchTitle: { color: theme.colors.text, fontSize: 13, fontWeight: '800' },
  onlinePill: {
    color: theme.colors.success,
    fontSize: 11,
    fontWeight: '800',
  },
  offlineAutoPill: {
    color: theme.colors.accent,
    fontSize: 11,
    fontWeight: '800',
  },
  modeSwitchRow: { flexDirection: 'row', gap: 8 },
  modeChip: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    borderRadius: theme.radius.pill,
    backgroundColor: theme.colors.surfaceRaised,
    borderWidth: 1,
    borderColor: theme.colors.borderSoft,
    paddingVertical: 11,
  },
  modeChipActive: {
    backgroundColor: theme.colors.primary,
    borderColor: theme.colors.primary,
  },
  modeChipText: { color: theme.colors.text, fontWeight: '800', fontSize: 12 },
  modeChipTextActive: { color: theme.colors.background },
  avatarBubble: {
    width: 50,
    height: 50,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: theme.colors.surfaceRaised,
    borderWidth: 1,
    borderColor: theme.colors.borderSoft,
  },
  homeToolbar: {
    flexDirection: 'row',
    gap: 10,
  },
  homeToolBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 11,
    borderRadius: 14,
    backgroundColor: theme.colors.surface,
    borderWidth: 1,
    borderColor: theme.colors.borderSoft,
  },
  homeToolText: {
    color: theme.colors.text,
    fontWeight: '700',
    fontSize: 12,
  },
  spotlightGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  spotlightTile: {
    width: '48.4%',
    borderRadius: 12,
    overflow: 'hidden',
    backgroundColor: '#232630',
    flexDirection: 'row',
    alignItems: 'center',
  },
  spotlightWideTile: {
    width: '100%',
  },
  spotlightCover: {
    width: 56,
    height: 56,
  },
  spotlightText: {
    color: theme.colors.text,
    fontSize: 13,
    fontWeight: '800',
    flex: 1,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  heroPanel: {
    minHeight: 210,
    borderRadius: theme.radius.xl,
    overflow: 'hidden',
    backgroundColor: theme.colors.surface,
    borderWidth: 1,
    borderColor: theme.colors.borderSoft,
  },
  heroImage: { width: '100%', height: '100%' },
  heroOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(7, 11, 18, 0.18)',
  },
  heroTextWrap: {
    position: 'absolute',
    left: 18,
    right: 18,
    bottom: 18,
    gap: 6,
  },
  heroKicker: { color: theme.colors.primary, fontWeight: '800', fontSize: 12 },
  heroTitle: { color: theme.colors.text, fontWeight: '900', fontSize: 24 },
  heroSub: { color: theme.colors.text, opacity: 0.84, lineHeight: 20 },
  statRow: { flexDirection: 'row', gap: 10 },
  statCard: {
    flex: 1,
    padding: 14,
    borderRadius: 18,
    backgroundColor: theme.colors.surface,
    borderWidth: 1,
    borderColor: theme.colors.borderSoft,
    gap: 6,
  },
  statIcon: {
    width: 30,
    height: 30,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: theme.colors.surfaceRaised,
  },
  statValue: { color: theme.colors.text, fontSize: 18, fontWeight: '900' },
  statLabel: { color: theme.colors.textMuted, fontSize: 11, fontWeight: '600' },
  quickActions: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  sectionHeader: { flexDirection: 'row', alignItems: 'flex-end', gap: 12 },
  sectionTitle: { color: theme.colors.text, fontSize: 20, fontWeight: '900' },
  sectionSub: { color: theme.colors.textMuted, fontSize: 12, marginTop: 4 },
  sectionAction: { color: theme.colors.primary, fontWeight: '800' },
  chip: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: theme.radius.pill,
    backgroundColor: theme.colors.surface,
    borderWidth: 1,
    borderColor: theme.colors.borderSoft,
  },
  chipActive: { backgroundColor: theme.colors.primary, borderColor: theme.colors.primary },
  chipText: { color: theme.colors.textMuted, fontWeight: '800', fontSize: 12 },
  chipTextActive: { color: theme.colors.background },
  horizontalRow: { gap: 12, paddingVertical: 6 },
  artistCard: {
    width: 132,
    padding: 12,
    borderRadius: 18,
    backgroundColor: theme.colors.surface,
    borderWidth: 1,
    borderColor: theme.colors.borderSoft,
    gap: 8,
  },
  artistImage: { width: '100%', aspectRatio: 1, borderRadius: 14 },
  artistName: { color: theme.colors.text, fontWeight: '900' },
  artistMeta: { color: theme.colors.textMuted, fontSize: 11 },
  playlistCard: {
    width: 160,
    padding: 12,
    borderRadius: 18,
    backgroundColor: theme.colors.surface,
    borderWidth: 1,
    borderColor: theme.colors.borderSoft,
    gap: 8,
  },
  playlistCover: { width: '100%', aspectRatio: 1, borderRadius: 14 },
  playlistTitle: { color: theme.colors.text, fontWeight: '900' },
  playlistSub: { color: theme.colors.textMuted, fontSize: 12 },
  pageTitle: { color: theme.colors.text, fontSize: 30, fontWeight: '900' },
  pageSub: { color: theme.colors.textMuted, marginTop: -6 },
  searchInput: {
    backgroundColor: theme.colors.surfaceRaised,
    borderWidth: 1,
    borderColor: theme.colors.borderSoft,
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 13,
    color: theme.colors.text,
  },
  resultPill: {
    padding: 14,
    borderRadius: 18,
    backgroundColor: theme.colors.surface,
    borderWidth: 1,
    borderColor: theme.colors.borderSoft,
    gap: 4,
  },
  resultPrimary: { color: theme.colors.primary, fontSize: 11, fontWeight: '800' },
  resultSecondary: { color: theme.colors.text, fontWeight: '800' },
  downloaderCard: {
    padding: 16,
    borderRadius: 18,
    backgroundColor: theme.colors.surface,
    borderWidth: 1,
    borderColor: theme.colors.borderSoft,
    gap: 10,
  },
  inputLabel: { color: theme.colors.textMuted, fontSize: 12, fontWeight: '700' },
  urlInput: {
    backgroundColor: theme.colors.surfaceRaised,
    borderWidth: 1,
    borderColor: theme.colors.borderSoft,
    borderRadius: 14,
    color: theme.colors.text,
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  formatRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  formatButton: {
    paddingHorizontal: 12,
    paddingVertical: 9,
    borderRadius: theme.radius.pill,
    backgroundColor: theme.colors.surfaceRaised,
    borderWidth: 1,
    borderColor: theme.colors.borderSoft,
  },
  formatButtonActive: {
    backgroundColor: theme.colors.primary,
    borderColor: theme.colors.primary,
  },
  formatButtonText: { color: theme.colors.text, fontWeight: '700', fontSize: 12 },
  formatButtonTextActive: { color: theme.colors.background },
  downloaderError: { color: theme.colors.danger, fontSize: 12, fontWeight: '700' },
  downloaderHint: { color: theme.colors.textMuted, fontSize: 11 },
  successBanner: {
    padding: 12,
    borderRadius: 14,
    backgroundColor: 'rgba(110, 231, 183, 0.16)',
    borderWidth: 1,
    borderColor: 'rgba(110, 231, 183, 0.45)',
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 6,
  },
  successBannerText: {
    color: theme.colors.success,
    fontWeight: '800',
    fontSize: 12,
    flex: 1,
  },
  errorBanner: {
    padding: 12,
    borderRadius: 14,
    backgroundColor: 'rgba(255, 106, 136, 0.12)',
    borderWidth: 1,
    borderColor: 'rgba(255, 106, 136, 0.4)',
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 6,
  },
  errorBannerText: {
    color: theme.colors.danger,
    fontWeight: '800',
    fontSize: 12,
    flex: 1,
  },
  demoBanner: {
    padding: 10,
    borderRadius: 12,
    backgroundColor: 'rgba(255, 184, 92, 0.10)',
    borderWidth: 1,
    borderColor: 'rgba(255, 184, 92, 0.35)',
    flexDirection: 'row' as const,
    alignItems: 'flex-start' as const,
    gap: 6,
  },
  demoBannerText: {
    color: theme.colors.accent,
    fontSize: 11,
    fontWeight: '600' as const,
    flex: 1,
    lineHeight: 16,
  },
  demoBadge: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: theme.radius.pill,
    backgroundColor: 'rgba(255, 184, 92, 0.15)',
    borderWidth: 1,
    borderColor: 'rgba(255, 184, 92, 0.4)',
  },
  demoBadgeText: {
    color: theme.colors.accent,
    fontSize: 10,
    fontWeight: '800' as const,
    letterSpacing: 0.5,
  },
  dlThumb: {
    width: 46,
    height: 46,
    borderRadius: 10,
    backgroundColor: theme.colors.surfaceRaised,
  },
  dlThumbFallback: {
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
  },
  dlPlayBtn: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    backgroundColor: theme.colors.primary,
  },
  dlPlayBtnPlaying: {
    backgroundColor: theme.colors.success,
  },
  dlActionBtn: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 5,
    borderRadius: 8,
    backgroundColor: theme.colors.surfaceRaised,
    borderWidth: 1,
    borderColor: theme.colors.borderSoft,
  },
  dlActionBtnText: {
    color: theme.colors.textMuted,
    fontSize: 11,
    fontWeight: '700' as const,
  },
  dlDangerText: {
    color: theme.colors.danger,
    fontSize: 11,
    fontWeight: '700' as const,
  },
  dlCardRow: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 10,
  },
  dlActionsRow: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    justifyContent: 'space-between' as const,
    gap: 8,
    flexWrap: 'wrap' as const,
    marginTop: 2,
  },
  nowPlayingBadge: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 3,
  },
  localTrackCard: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    padding: 12,
    borderRadius: 14,
    backgroundColor: theme.colors.surface,
    borderWidth: 1,
    borderColor: theme.colors.borderSoft,
    gap: 12,
  },
  localTrackIconWrap: {
    width: 42,
    height: 42,
    borderRadius: 10,
    backgroundColor: theme.colors.surfaceRaised,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
  },
  localTrackTitle: {
    color: theme.colors.text,
    fontWeight: '700' as const,
    fontSize: 14,
  },
  localTrackMeta: {
    color: theme.colors.textMuted,
    fontSize: 11,
    marginTop: 2,
  },
  offlineBanner: {
    padding: 12,
    borderRadius: 12,
    backgroundColor: 'rgba(83, 214, 196, 0.10)',
    borderWidth: 1,
    borderColor: 'rgba(83, 214, 196, 0.3)',
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 8,
  },
  offlineBannerText: {
    color: theme.colors.primary,
    fontSize: 12,
    fontWeight: '700' as const,
    flex: 1,
  },
  localControlCard: {
    padding: 14,
    borderRadius: 16,
    backgroundColor: theme.colors.surface,
    borderWidth: 1,
    borderColor: theme.colors.borderSoft,
    gap: 8,
  },
  localControlSub: { color: theme.colors.textMuted, fontSize: 12 },
  localControlStatus: { color: theme.colors.success, fontSize: 12, fontWeight: '700' },
  localControlActions: { flexDirection: 'row', gap: 8, flexWrap: 'wrap' },
  localFilesCard: {
    padding: 14,
    borderRadius: 16,
    backgroundColor: theme.colors.surface,
    borderWidth: 1,
    borderColor: theme.colors.borderSoft,
    gap: 6,
  },
  localFileRow: { color: theme.colors.text, fontSize: 12 },
  historyCard: {
    padding: 12,
    borderRadius: 14,
    backgroundColor: theme.colors.surface,
    borderWidth: 1,
    borderColor: theme.colors.borderSoft,
    flexDirection: 'row',
    gap: 10,
    alignItems: 'center',
  },
  historyThumb: {
    width: 54,
    height: 54,
    borderRadius: 10,
    backgroundColor: theme.colors.surfaceRaised,
  },
  historyThumbFallback: {
    width: 54,
    height: 54,
    borderRadius: 10,
    backgroundColor: theme.colors.surfaceRaised,
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.55)',
    justifyContent: 'flex-end',
  },
  modalCard: {
    maxHeight: '82%',
    backgroundColor: theme.colors.backgroundAlt,
    borderTopLeftRadius: 22,
    borderTopRightRadius: 22,
    paddingHorizontal: 16,
    paddingTop: 14,
  },
  modalTopBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  modalTitle: { color: theme.colors.text, fontSize: 18, fontWeight: '900' },
  downloadsHeaderRow: {
    marginTop: 4,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  downloadItemCard: {
    padding: 14,
    borderRadius: 16,
    backgroundColor: theme.colors.surface,
    borderWidth: 1,
    borderColor: theme.colors.borderSoft,
    gap: 8,
  },
  downloadItemTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 10,
  },
  downloadItemTitle: { color: theme.colors.text, fontWeight: '800', flex: 1 },
  downloadItemFormat: { color: theme.colors.primary, fontWeight: '800', fontSize: 11 },
  downloadItemMeta: { color: theme.colors.textMuted, fontSize: 12 },
  nowPlayingInline: {
    color: theme.colors.success,
    fontSize: 11,
    fontWeight: '800',
  },
  downloadProgressTrack: {
    height: 6,
    borderRadius: 999,
    backgroundColor: theme.colors.borderSoft,
    overflow: 'hidden',
  },
  downloadProgressFill: {
    height: 6,
    backgroundColor: theme.colors.primary,
  },
  downloadItemActions: {
    flexDirection: 'row',
    gap: 8,
    flexWrap: 'wrap',
  },
  infoCard: {
    padding: 16,
    borderRadius: 18,
    backgroundColor: theme.colors.surface,
    borderWidth: 1,
    borderColor: theme.colors.borderSoft,
    gap: 6,
  },
  infoLabel: { color: theme.colors.textMuted, fontSize: 11, fontWeight: '700' },
  infoValue: { color: theme.colors.text, fontWeight: '800', marginBottom: 6 },
  actionRow: { flexDirection: 'row', gap: 10, flexWrap: 'wrap' },
  actionRowCentered: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 10 },
  playerPage: {
    padding: theme.spacing.lg,
    gap: theme.spacing.md,
    paddingBottom: 140,
  },
  playerArtWrap: {
    borderRadius: 32,
    overflow: 'hidden',
    backgroundColor: theme.colors.surface,
    borderWidth: 1,
    borderColor: theme.colors.borderSoft,
  },
  playerArt: { width: '100%', aspectRatio: 1 },
  playerGlow: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(83, 214, 196, 0.08)',
  },
  playerTitle: { color: theme.colors.text, fontSize: 28, fontWeight: '900' },
  playerArtist: { color: theme.colors.textMuted, fontSize: 15 },
  progressHeader: { flexDirection: 'row', justifyContent: 'space-between' },
  progressTime: { color: theme.colors.textMuted, fontSize: 12, fontWeight: '600' },
  playerProgressTrack: {
    height: 6,
    borderRadius: 999,
    backgroundColor: theme.colors.borderSoft,
    overflow: 'hidden',
  },
  playerProgressFill: { height: 6, backgroundColor: theme.colors.primary },
  circleBtn: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: theme.colors.surfaceRaised,
    borderWidth: 1,
    borderColor: theme.colors.borderSoft,
  },
  circleBtnActive: { backgroundColor: theme.colors.primary },
  mainPlayBtn: {
    width: 64,
    height: 64,
    borderRadius: 32,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: theme.colors.primary,
  },
  queueCard: {
    padding: 16,
    borderRadius: 18,
    backgroundColor: theme.colors.surface,
    borderWidth: 1,
    borderColor: theme.colors.borderSoft,
    gap: 10,
  },
  queueTitle: { color: theme.colors.text, fontWeight: '900', fontSize: 16 },
  queueRow: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  queueCover: { width: 42, height: 42, borderRadius: 12 },
  queueItemTitle: { color: theme.colors.text, fontWeight: '800' },
  queueSub: { color: theme.colors.textMuted, fontSize: 12 },
});
